-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.regions
(
    id character varying(3) NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.municips
(
    id character varying(5) NOT NULL,
    region_id character varying(3) NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.towns
(
    id serial,
    municip_id character varying(5) NOT NULL,
    ekatte character varying(5) NOT NULL,
    type character varying(4) NOT NULL,
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.municips
    ADD FOREIGN KEY (region_id)
    REFERENCES public.regions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.towns
    ADD FOREIGN KEY (municip_id)
    REFERENCES public.municips (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
